name: Need Feature
description: Need new features and hope to get support
labels: []
body:
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please describe the feature need and usage scenarios.
      placeholder: Description
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Template Name
      description: Please select a template
      options:
        - masablazor-server
        - masablazor-wasm
        - masablazor-empty-server
        - masablazor-empty-wasm
        - masablazor-pro-server
        - masablazor-pro-wasm
        - masablazor-maui
        - masafx
        - masafx-service
        - masafx-service-cqrs
    validations:
      required: true