name: Mirror to Giltab
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: yesolutions/mirror-action@v0.5.1
        with:
          REMOTE: '${{ secrets.GITLAB_ADDER }}/cicd/MASA.Templates.git'
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
