name: Push nuget package manually
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the package, no "v" prefix'
        required: true
        default: '1.0.0'

jobs:
  push-nuget-manually:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: pack
      run: dotnet pack src/src.csproj -c Release -p:PackageId=Masa.Template -p:PackageVersion=${{github.event.inputs.version}} -p:NoBuild=true
    - name: package push
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_TOKEN}}  -s https://api.nuget.org/v3/index.json